### PR TITLE
Create pt-br

### PR DESCRIPTION
**Pull request by Havokdan**

### CODE REVIEW

**Comment by Sopor-** [comment]
Why did you not translated everything?
```
+    [+!#]addrel <CATEGORY> <RELEASENAME>
+    [+!#]releases <CATEGORY>
+    [+!#]delrel <RELEASE-ID>
+    [+!#]reloadrel
+    [+!#]searchrel <SEARCH-STRING>
+    [+!#]prunerel [<MAX-RELEASE-AGE>]
+    [+!#]topadders
+    [+!#]relhelp
+    [+!#]announcerel <REAL-DUMP-NICKNAME> <CATEGORY> <RELEASENAME>
+    [+!#]reldesligado
+    [+!#]relon
```
You need to give the pull request a more useful name. How should i know by looking at the PR where this should be? All your PR have the same name "Create pt-br"

**Comment by Havokdan** [comment]
Sorry, I thought the folder where you requested was. As it was commands, I chose to put where it has commands, leave original.

**Comment by Sopor-** [comment]
This is the command `[+!#]addrel` but not `<CATEGORY> <RELEASENAME>`

**Comment by Sopor-** [comment]
I'm sure if it is a great idea to put the lang files in the source. It will be too much work to update all the zip files. How many users will look in the source folder after other lang files? Most users will download the zip.

**Comment by Havokdan** [comment]
> I'm not sure if it is a great idea to put the lang files in the source. It will be too much work to update all the zip files. How many users will look in the source folder after other lang files? Most users will download the zip. Any suggestions?

I put them there because they are not in the translation repository, what about creating for these scripts and moving my translation there? It's possible?

**Comment by Sopor-** [comment]
The scripts are made by all kind of users so i have no plan to move the translation there. If you want to add more translations (PR) please put them in the additional_language folder as i have done it.

**Comment by Havokdan** [comment]
OK

**Pull request merged**
